### PR TITLE
Add lazy loader for yarn if present

### PR DESCRIPTION
**Pull request by lukechilds**
Fixes https://github.com/lukechilds/zsh-nvm/issues/16

### CODE REVIEW

**Comment by lukechilds** [comment]
@SimenB This should resolve your problem, are you able to test it and let me know before I merge into master?

**Comment by SimenB** [comment]
Yeah, I can give it a whirl tomorrow!

**Comment by SimenB** [comment]
It works! Thanks 😄

**Comment by lukechilds** [comment]
Sweet, merged!

**Comment by lukechilds** [comment]
@SimenB Sweet, merged!

**Pull request merged**
